export const skills = [
  "Adaptability",
  "Ajax",
  "Amazon Web Services (AWS)",
  "Android Development",
  "Angular",
  "Ansible",
  "Asana",
  "AWS",
  "Azure",
  "Big Data Analytics",
  "Bitbucket",
  "Bootstrap",
  "Bulma",
  "Chef",
  "CI/CD",
  "CircleCI",
  "Clustering",
  "C++",
  "C#",
  "Communication",
  "Computer Vision",
  "Configuration Management",
  "Conflict Resolution",
  "Containers",
  "Continuous Integration/Continuous Deployment (CI/CD)",
  "Copywriting",
  "Creativity",
  "Creative Writing",
  "CSS",
  "CSS3",
  "Data Analysis",
  "Data Mining",
  "Data Science",
  "Data Visualization",
  "Decision Making",
  "Deep Learning",
  "DevOps",
  "Digital Art",
  "Django",
  "Docker",
  "Editing",
  "Emotional Intelligence",
  "Empathy",
  "Express",
  "Feedback",
  "Firebase",
  "Flask",
  "Flutter",
  "Foundation",
  "GitHub",
  "Git",
  "GitLab",
  "Google Cloud",
  "GraphQL",
  "Graphic Design",
  "Hadoop",
  "Heroku",
  "Hibernate",
  "HTML",
  "HTML5",
  "Illustration",
  "Infrastructure as Code (IaC)",
  "iOS",
  "Jira",
  "JPA",
  "Jenkins",
  "Jira",
  "JPA",
  "JSP",
  "jQuery",
  "JWT",
  "Keras",
  "Kotlin",
  "Kubernetes",
  "Leadership",
  "Less",
  "Machine Learning",
  "Materialize",
  "Matplotlib",
  "Microsoft Azure",
  "Microservices",
  "MongoDB",
  "Monitoring",
  "Natural Language Processing",
  "Negotiation",
  "Netlify",
  "Networking",
  "Neural Networks",
  "NoSQL",
  "NumPy",
  "Object-Oriented Programming (OOP)",
  "OAuth",
  "Objective-C",
  "OpenStack",
  "Orchestration",
  "Pandas",
  "Photo Editing",
  "Photography",
  "Phaser",
  "Presentation Skills",
  "Problem-Solving",
  "Proofreading",
  "PyTorch",
  "Python",
  "React",
  "React Native",
  "Regression Analysis",
  "Reinforcement Learning",
  "Resilience",
  "REST",
  "R",
  "Ruby on Rails",
  "Sass",
  "Scikit-learn",
  "Serverless Architecture",
  "Servlets",
  "SOAP",
  "Socket.IO",
  "Soft Skills",
  "Spark",
  "Spring",
  "SQL",
  "SQL",
  "Statistical Analysis",
  "Storyboarding",
  "Stress Management",
  "Swift",
  "Symfony",
  "Teamwork",
  "Technical Writing",
  "TensorFlow",
  "Time Management",
  "Trello",
  "Troubleshooting",
  "Typography",
  "Unity",
  "Unreal Engine",
  "Vercel",
  "Video Editing",
  "Vue",
  "WebAssembly",
  "WebRTC",
  "WebSockets",
  "Webpack",
  "Wordpress",
  "Writing",
  "Xamarin",
];
